server:
  port: 8040
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/comment-service
    url: jdbc:postgresql://localhost:5432/review-monolith
    username: seyan99
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    review-url: http://localhost:8222/api/v1/reviews
    list-url: http://localhost:8222/api/v1/lists