server:
  port: 8020
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/film-service
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    review-url: http://localhost:8222/api/v1/reviews
    activity-url: http://localhost:8222/api/v1/activities
