server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: activity-service
          uri: lb:http://ACTIVITY-SERVICE
          predicates:
            - Path=/api/v1/activities/**
        - id: film-service
          uri: lb:http://FILM-SERVICE
          predicates:
            - Path=/api/v1/films/**
        - id: review-service
          uri: lb:http://REVIEW-SERVICE
          predicates:
            - Path=/api/v1/reviews/**
        - id: list-service
          uri: lb:http://LIST-SERVICE
          predicates:
            - Path=/api/v1/lists/**
        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
