server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/list-service
    url: jdbc:postgresql://localhost:5432/review-monolith
    username: seyan99
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    film-url: http://localhost:8222/api/v1/films
    comment-url: http://localhost:8222/api/v1/comments