server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/review-service
    url: jdbc:postgresql://localhost:5432/review-monolith
    username: seyan99
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    activity-url: http://localhost:8222/api/v1/activities
    film-url: http://localhost:8222/api/v1/films